### PR TITLE
[-] MO: ganalytics: using HookOrderConfirmation

### PR DESCRIPTION
**Pull request by kermes**
Payment modules with their own own confirmation controller wont be recorded, instead of looking for the the controller ordercontroller this should be executed in the hook orderConfirmation

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @kermes,

Updating the upgrade file is a good idea, however the module version is currently 2.0.4. It will be better to create a new one for the version 2.0.5, which registers the hook orderConfirmation and unregister the hook top.

Regards

**Comment by cedricfontaine** [comment]
Hook OrderConfirmation is deprecated in 1.6. Is there any alternate way to execute an hook when creating an order ?

**Comment by Quetzacoalt91** [comment]
Indeed, the new one is DisplayOrderConfirmation. But like the other hooks already existing in 1.4, the alias table does the relation between them.

**Comment by cedricfontaine** [comment]
So we can use HookOrderConfirmation ?

**Comment by Quetzacoalt91** [comment]
Yes, I do not see any issue with that hook.

**Comment by kermes** [comment]
At first I used the displayOrderConfirmation hook but I changed back for
backwards compatibility

**Comment by cedricfontaine** [comment]
Could you change your upgrade file to 2_0_5 ? And we can merge this one.
After I think we can release this new version.

**Comment by kermes** [comment]
Done

**Comment by Quetzacoalt91** [comment]
Hi @kermes & @cedricfontaine,

This PR has been merged on the dev branch for testing purpose.
I modified the upgrade file to leave only the new hook:
```php
function upgrade_module_2_0_5($object)
{
	Configuration::updateValue('GANALYTICS', '2.0.5');
	return ($object->registerHook('orderConfirmation')
		&& $object->unregisterHook('top'));
}
```

**Pull request merged**
