### PR TITLE
[-] MO : Page view isnt tracked since 2.0

### PR DESCRIPTION
**Pull request by Elitius**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Best regards

**Comment by kermes** [comment]
NO NO!!
pageview is sent in line 583 and it depends on some factors, we made a lot of effort to prevent pageview being sent too many times, because some events NEED a pageview, to reduce it to only one time. if you do this it will always be sent twice!

**Comment by kermes** [comment]
Thank god, I just saw @jeromenadaud made this commit to revert it:
https://github.com/PrestaShop/ganalytics/commit/867b663210283455b922cb3a4a18805db6f4e9df

**Comment by Quetzacoalt91** [comment]
Hi,

Indeed, we made a revert this morning after I saw that pageview is now sent multiple times.
As we explain earlier this week on [Twitter](https://twitter.com/PrestaPlugins/status/569452932091027456) (in French), the pageview is executed a the end of the module execution to be sure to send it only one time.

Regards

**Comment by Elitius** [comment]
I'm sorry but its the 3rd time I test ganalytics module sinced 2.0 update and I never get page tracking without this. Where is the problem so ?

**Comment by Quetzacoalt91** [comment]
The hooks have changed from the version 2.0.X and maybe your module has not been properly updated from these versions.
Can you please try to uninstall / install and check if the problem still appear ? Thanks.

**Comment by Elitius** [comment]
Doesnt work :/ I get analytics infos on my pages but no send :/

				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
				ga('create', 'UA-1234567-1', 'auto');
				ga('require', 'ec');

**Comment by Elitius** [comment]
OK module was not on footer's hook. Sorry for the issue!

**Pull request merged**
