### PR TITLE
[*MO] : Avoid cookie overflow

### PR DESCRIPTION
**Pull request by cedricfontaine**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @cedricfontaine,

I have just tried this version by adding quantity to a product already in the cart, and got the following notices in the AJAX result:
capture du 2015-03-18 12 17 49

**Comment by cedricfontaine** [comment]
Hello,

Could you retry now ?

**Comment by Quetzacoalt91** [comment]
Hi @cedricfontaine,

I'm now getting this error when I add a product to the cart:
capture du 2015-03-20 15 29 21

**Comment by cedricfontaine** [comment]
Ok should be ok now.

**Comment by Quetzacoalt91** [comment]
Hi @cedricfontaine,

Yeah it is really better now, and the issue with the cookie is now fixed.

Your PR has just been merged and will be available for the next version. :)

Regards

**Comment by cedricfontaine** [comment]
Hello,

Could we release it as soon as possible ?

**Comment by Quetzacoalt91** [comment]
Hi,

The merge on the master is already done. The version 2.0.9 will be
available tomorrow. :)

**Pull request merged**
