### PR TITLE
Patch 21

### PR DESCRIPTION
**Pull request by rdonato**
You should set this property:

curl_setopt($ch,CURLOPT_RETURNTRANSFER, TRUE);

to avoid this kind of echo on the frontend after order-confirmation

GIF89a�����,D;

### CODE REVIEW

**Comment by kermes** [comment]
Thank you, already fixed it.
I'm glad to know somebody else is giving it a try.

**Comment by rdonato** [comment]
Thanks, 

Unfortunately I still have problems on google analytics stats, Product quantities in Product performance report are all to zero.

**Comment by kermes** [comment]
I've see that too. I'm focusing right now in having at least the correct transactions. It's unusable like master branch is right now with so many duplicates and/or missing transactions.

**Comment by Quetzacoalt91** [comment]
Hi everybody,

Instead of creating a new PR, you should have posted on #41.
Because this one won't be merged, I let you update the other one if needed.

Regards

**Pull request closed without merging**
