### PR TITLE
[-] MO ganalytics: send transaction server-side (no duplicated or missing transactions)

### PR DESCRIPTION
**Pull request by kermes**
no duplicated transactions, no missing transactions
but.... needs curl

### CODE REVIEW

**Comment by kermes** [comment]
If this is finally merged, I thinks we should make all the backoffice events serverside.

**Comment by Elitius** [comment]
Hi,
I got a question about this commit.
Actually transactions are sent with displayOrderConfirmation hook.. but if a customer exit website before order confirmation page is displayed (for ex, on Paybox, when "transaction accepted" is displayed, and customer close the page before redirection to the shop), the hook is called or not ?
Maybe this commit can be a solution to this issue, but I think we should call actionValidateOrder instead ?

**Comment by kermes** [comment]
Yes, I was waiting for prestashop staff to review the commit before
submitting that change because it require a new hook registration and a nee
update file for the new version and did'nt want to create it before knowing
the version it would be included

**Comment by cedricfontaine** [comment]
This solution is not optimal because it does allow to track conversion path.
The actual way to handle it seems to work in 2.1

**Comment by Elitius** [comment]
Hi,

I still have missing lot of transactions with 2.2.1.

**Comment by cedricfontaine** [comment]
Do you have those transaction in the table ps_ganalytics ?

**Pull request closed without merging**
