### PR TITLE
Avoid sending orders older than 1 day

### PR DESCRIPTION
**Pull request by cedricfontaine**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @cedricfontaine,

This PR seems to be related to #79. However, I am not sure that the issue will be solved because the module will still try to send the data in the back-office, right ?

**Comment by cedricfontaine** [comment]
You're right. I merged it on the wrong hook.

**Comment by cedricfontaine** [comment]
Ok push it back in #PR83

**Comment by Quetzacoalt91** [comment]
So, should I close this PR ?

**Comment by cedricfontaine** [comment]
Yes, right

**Comment by Quetzacoalt91** [comment]
Okay thanks.

**Pull request closed without merging**
