### PR TITLE
[*] MO ganalytics: track carrier and payment method

### PR DESCRIPTION
**Pull request by kermes**
please, test first!

### CODE REVIEW

**Comment by cedricfontaine** [comment]
Hello,

I will test it this week, but I think we should stabilize the module before adding new features.

**Comment by cedricfontaine** [comment]
addCheckout is already implemented in the module.
See MBG.addCheckout

**Comment by kermes** [comment]
I thought it was easier to have another function just for that, as this one needs to send an event and it would require the other function to check if the 'option' parameter has been set or not, but this can be changed

**Comment by cedricfontaine** [comment]
Each step of the checkout is already sent using the step value.

**Comment by kermes** [comment]
Step, yes. Option, no. So no info about wich carrier has been selected or wich payment option has been chosen.
Just one example:
I someone selects carrier A, then go to next step, and change their mind, go back and select another carrier, you loose that info and you dont know wich carrier is the one being discarded so much.

**Comment by ZiZuu-store** [comment]
is this a dead PR? :( it would be nice to have the module to report as much info as possible

**Comment by kermes** [comment]
I've been using it for 8 months now. You can make an override of the module and test it yourself. I'm using an enhanced version where I send the checkout steps and options in one-pagecheckout straight from order-opc.js. Since we can't add hooks there, I haven't published it here because we cant add module specific code to the standard javascript.

**Comment by cedricfontaine** [comment]
Hello,

I'd like to include it in a next release. Could you update your modification ?

Thanks a lot.

**Comment by kermes** [comment]
I'll do it as soon as possible.

**Comment by gloomybear** [comment]
@cedricfontaine when do you expect to incude this feature? Looks really usefull!

**Comment by kermes** [comment]
I'm sorry I couldn't update it. I've been having some personal issues and
I'm short of time at this moment

2016-02-16 8:26 GMT+01:00 gloomybear <notifications@github.com>:

**Comment by kermes** [comment]
Made a new PR instead of modify this one. Was easier
https://github.com/PrestaShop/ganalytics/pull/93

**Pull request closed without merging**
